Bulding-Vistor-Management/Bulding-Vistor-Management-master/Bulding-Vistor-Management/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bulding_Vistor_Management.Models;

namespace Bulding_Vistor_Management.Controllers
{
    public class RecordsController : Controller
    {
        private Entities db = new Entities();

        // GET: Records
        public ActionResult Index()
        {
            var records = db.Records.Include(r => r.Appartment).Include(r => r.Tenant).Include(r => r.Visitor);
            return View(records.ToList());
        }

        // GET: Records/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // GET: Records/Create
        public ActionResult Create()
        {
            ViewBag.AppartmentId = new SelectList(db.Appartments, "AppartmentId", "AppartmentNumber");
            ViewBag.TenantId = new SelectList(db.Tenants, "TenantId", "TenantFullnames");
            ViewBag.VisitorId = new SelectList(db.Visitors, "VisitorId", "Fullnames");
            return View();
        }

        // POST: Records/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecordId,VisitorId,Date,Time,TenantId,AppartmentId")] Record record)
        {
            if (ModelState.IsValid)
            {
                db.Records.Add(record);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AppartmentId = new SelectList(db.Appartments, "AppartmentId", "AppartmentNumber", record.AppartmentId);
            ViewBag.TenantId = new SelectList(db.Tenants, "TenantId", "TenantFullnames", record.TenantId);
            ViewBag.VisitorId = new SelectList(db.Visitors, "VisitorId", "Fullnames", record.VisitorId);
            return View(record);
        }

        // GET: Records/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            ViewBag.AppartmentId = new SelectList(db.Appartments, "AppartmentId", "AppartmentNumber", record.AppartmentId);
            ViewBag.TenantId = new SelectList(db.Tenants, "TenantId", "TenantFullnames", record.TenantId);
            ViewBag.VisitorId = new SelectList(db.Visitors, "VisitorId", "Fullnames", record.VisitorId);
            return View(record);
        }

        // POST: Records/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RecordId,VisitorId,Date,Time,TenantId,AppartmentId")] Record record)
        {
            if (ModelState.IsValid)
            {
                db.Entry(record).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AppartmentId = new SelectList(db.Appartments, "AppartmentId", "AppartmentNumber", record.AppartmentId);
            ViewBag.TenantId = new SelectList(db.Tenants, "TenantId", "TenantFullnames", record.TenantId);
            ViewBag.VisitorId = new SelectList(db.Visitors, "VisitorId", "Fullnames", record.VisitorId);
            return View(record);
        }

        // GET: Records/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Record record = db.Records.Find(id);
            if (record == null)
            {
                return HttpNotFound();
            }
            return View(record);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Record record = db.Records.Find(id);
            db.Records.Remove(record);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bulding-Vistor-Management/Bulding-Vistor-Management-master/Bulding-Vistor-Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Indlu Place Appartments", "Index", "Records", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Record", "Index", "Records")</li>
                    <li>@Html.ActionLink("Visitors", "Index", "Visitors")</li>
                    <li>@Html.ActionLink("Tenants", "Index", "Tenants")</li>
                    <li>@Html.ActionLink("Appartments", "Index", "Appartments")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>